### ISSUE TITLE
Add to toltec

### ISSUE THREAD

**Issue by Eeems** [RedTeamPentesting/remarkable-encryption#1]
This should be added to toltec to make it easier for users to install it.

**Comment by rtpt-erikgeiser** [comment]
Due to the manual setup process it would still not be possible to easily use this project for inexperienced users. Currently, we have no plans to automate the setup due to our limited scope of deployment. If the maintainers of `toltec` still want it to be added they can do it, but we cannot test the project in the context their packaging solution.

**Comment by Eeems** [comment]
From what I'm seeing in the readme, It could all be automated by package install/uninstall/upgrade scripts.

**Comment by rtpt-erikgeiser** [comment]
Yes it will probably work. However, it is out of scope for this project. You could try opening an issue in the `toltec` repository.

**Comment by Eeems** [comment]
It's already in the package requests.

**Comment by rtpt-erikgeiser** [comment]
Awesome :rocket:

**Comment by queesamor** [comment]
@Eeems Did you ever get any movement from Toltec on this? I'm not seeing it in their package list. 😒

**Comment by Eeems** [comment]
It's in the package requests still I believe. Nobody has packaged it yet.
